### ISSUE TITLE
Armoures Workshop Mohist

### ISSUE THREAD

**Issue by GizzaGander** [Shevchik/ModFixNG#4]
[08:52:53 WARN]: [ModFixNG] Task #4 for ModFixNG v1.0 generated an exception
 java.lang.Error: Unresolved compilation problem:
        The method a(Slot) in the type Container is not applicable for the arguments (EntityHuman)

        at modfixng.nms.utils.v1_12_R1.NMSUtils.isInventoryValid(NMSUtils.java:70) ~[?:?]
        at modfixng.fixes.ProperlyCloseBlocksContainers.isValid(ProperlyCloseBlocksContainers.java:135) ~[?:?]
        at modfixng.fixes.ProperlyCloseBlocksContainers.access$1(ProperlyCloseBlocksContainers.java:134) ~[?:?]
        at modfixng.fixes.ProperlyCloseBlocksContainers$1.run(ProperlyCloseBlocksContainers.java:123) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:1.12.2-f1df30a]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:1.12.2-f1df30a]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[08:52:53 ERROR]: TIMING_STACK_CORRUPTION - Report this to the plugin ModFixNG(Look for errors above this in the logs) (TimingIdentifier{id=ModFixNG:Task: modfixng.fixes.ProperlyCloseBlocksContainers$1 (interval:1)} did not stopTiming)
 java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:1.12.2-f1df30a]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Shevchik** [comment]
This project is not supported (Just like any other in this pseudo org).

And the problem is there anyway:
```
java.lang.Error: Unresolved compilation problem:
The method a(Slot) in the type Container is not applicable for the arguments (EntityHuman)
```
You compiled what doesn't actually compile on your platform.
